#   This dockerfile is copied from miking-dockerfiles with the caveat that tests
#   have been remove. It has the following license
#   
#     MIT License
#     
#     Copyright (c) 2022 Miking
#     
#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:
#     
#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.
#     
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.
#    

ARG MIKING_IMAGE
FROM ${MIKING_IMAGE}

# Download the latest version of the miking repository
ARG MIKING_DPPL_GIT_REMOTE
ARG MIKING_DPPL_GIT_COMMIT
RUN mkdir -p /src \
 && cd /src \
 && git clone ${MIKING_DPPL_GIT_REMOTE} \
 && cd /src/miking-dppl \
 && git checkout ${MIKING_DPPL_GIT_COMMIT} \
 && echo "MIKING_DPPL_GIT_REMOTE=\"$MIKING_DPPL_GIT_REMOTE\"" >> /root/imgbuild_flags.txt \
 && echo "MIKING_DPPL_GIT_COMMIT=\"$MIKING_DPPL_GIT_COMMIT\"" >> /root/imgbuild_flags.txt

WORKDIR /src/miking-dppl

RUN eval $(opam env) \
 && make install \
 && make clean

WORKDIR /root

ENV MCORE_LIBS="coreppl=/root/.local/src/coreppl:$MCORE_LIBS"

CMD ["cppl"]