# This dockerfile is copied from
# 
#   https://github.com/miking-lang/miking-docker/blob/main/Dockerfile-miking-dppl
# 
# It is used as is, except that tests have been removed.

ARG MIKING_IMAGE
FROM ${MIKING_IMAGE}

# Download the latest version of the miking repository
ARG MIKING_DPPL_GIT_REMOTE
ARG MIKING_DPPL_GIT_COMMIT
RUN mkdir -p /src \
 && cd /src \
 && git clone ${MIKING_DPPL_GIT_REMOTE} \
 && cd /src/miking-dppl \
 && git checkout ${MIKING_DPPL_GIT_COMMIT} \
 && echo "MIKING_DPPL_GIT_REMOTE=\"$MIKING_DPPL_GIT_REMOTE\"" >> /root/imgbuild_flags.txt \
 && echo "MIKING_DPPL_GIT_COMMIT=\"$MIKING_DPPL_GIT_COMMIT\"" >> /root/imgbuild_flags.txt

WORKDIR /src/miking-dppl

RUN eval $(opam env) \
 && make install \
 && make clean

WORKDIR /root

ENV MCORE_LIBS="coreppl=/root/.local/src/coreppl:$MCORE_LIBS"

CMD ["cppl"]