# This dockerfile is modeled on the Miking lang dockerfiles in
# 
#   https://github.com/miking-lang/miking-docker/
# 

ARG MIKING_DPPL_IMAGE
FROM ${MIKING_DPPL_IMAGE}

# Download the latest version of the miking repository
ARG TREEPPL_GIT_REMOTE="https://github.com/treeppl/treeppl.git"
ARG TREEPPL_GIT_COMMIT="a2259e3"
RUN mkdir -p /src \
 && cd /src \
 && git clone ${TREEPPL_GIT_REMOTE} \
 && cd /src/treeppl \
 && git checkout ${TREEPPL_GIT_COMMIT} \
 && echo "TREEPPL_GIT_REMOTE=\"$TREEPPL_GIT_REMOTE\"" >> /root/imgbuild_flags.txt \
 && echo "TREEPPL_GIT_COMMIT=\"$TREEPPL_GIT_COMMIT\"" >> /root/imgbuild_flags.txt

WORKDIR /src/treeppl

RUN eval $(opam env) \
 && make install \
 && make clean

WORKDIR /root

ENV MCORE_LIBS="treeppl=/root/.local/src/treeppl:$MCORE_LIBS"

CMD ["tpplc"]