FROM r-base:4.4.2

RUN Rscript -e "install.packages('pak', repos = 'https://r-lib.github.io/p/pak/dev/'); pak::pkg_install(c('ape', 'tidyverse', 'jsonlite')); pak::pkg_install('maribraga/evolnets'); pak::pkg_install('treeppl/treepplr@bd4e27e')"
